### ISSUE TITLE
✨ 전반적인 예외 처리

### ISSUE THREAD

**Issue by helenason** [woowacourse-teams/2024-chongdae-market#101]
## 📌 Description
- 전반적인 예외 처리 핸들러 추가

## 📝 To-do
- [x] 예외 처리 핸들러 추가
- [x] 도메인 검증 로직 추가
- [x] DTO 검증 로직 추가

## 예상 소요 시간
- 0.5h
- `1h`
- 1.5h
- 2h
- 2.5h
- 3h+
