### ISSUE TITLE
✨ 댓글방 목록 뷰 구현

### ISSUE THREAD

**Issue by songpink** [woowacourse-teams/2024-chongdae-market#11]
## 📌 Description
- 댓글방 목록 뷰를 구현한다.
![image](https://github.com/user-attachments/assets/41d4d289-1fc3-4d9e-80c4-63df8c02fea1)

## 📝 To-do
- [ ] 댓글방을 목록을 Recycler View로 구현한다.
- [ ] 자신이 총대인 방과 참여자인 방을 구별할 수 있어야 한다.
- [ ] 참여중인 댓글방이 없다면 "아직 채팅 목록이 없어요" 라는 뷰를 띄워야 한다.

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- 3h+
- `1d`
