### ISSUE TITLE
✨ 홈화면 API 연결

### ISSUE THREAD

**Issue by Namyunsuk** [woowacourse-teams/2024-chongdae-market#12]
## 📌 Description
- 홈화면과 Api를 연결한다.

## 📝 To-do
- [x] data layer 수정
- [x] presentation layer 연결
- [x] 상태에 따른 뷰를 보여주도록 구현

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
`- 3h+`
