### ISSUE TITLE
♻️ 공모에 저장하는 주소 값 구체화

### ISSUE THREAD

**Issue by helenason** [woowacourse-teams/2024-chongdae-market#140]
## 📌 Description
- 목록 조회 시 [동] 필드를 조회하기 위해 [동] 필드 추가 저장

## 📝 To-do
- [x] DB 컬럼에 [동] 추가
- [x] 공모 저장 API: [동] 필드 함께 저장
- [x] 공모 목록 조회 API: [동] 필드만 조회
- [x] 공모 상세 조회 API: [도로명 주소+상세주소]으로 조회
- [x] 댓글방 위치 확인 API: [도로명 주소+상세주소]으로 조회

## 예상 소요 시간
- 0.5h
- `1h`
- 1.5h
- 2h
- 2.5h
- 3h+
