### ISSUE TITLE
♻️ 제품 코드와 API 문서 동기화

### ISSUE THREAD

**Issue by helenason** [woowacourse-teams/2024-chongdae-market#151]
## 📌 Description
- 제품 코드에서 제공하는 API와 API 문서 내용이 일치하지 않아 이를 맞춥니다.  

## 📝 To-do
- [x] 테스트 request 형태를 Map에서 DTO로 변경
- [x] 문서화 description 내 optional 정보 추가
- [x] 예외 처리에 대한 문서화

## 예상 소요 시간
- 0.5h
- `1h`
- 1.5h
- 2h
- 2.5h
- 3h+
