### ISSUE TITLE
✨ 상태 변경 API 구현

### ISSUE THREAD

**Issue by helenason** [woowacourse-teams/2024-chongdae-market#158]
## 📌 Description
- 상태 변경 API를 구현합니다.

## 📝 To-do
- [x] 공모 테이블에 상태 필드 추가
- [x] 상태 도메인 설계
- [x] 상태 변경 API 구현

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- `3h+`
