### ISSUE TITLE
✨ 로그인 기능 구현 

### ISSUE THREAD

**Issue by ChooSeoyeon** [woowacourse-teams/2024-chongdae-market#160]
## 📌 Description
- 회원 로그인 기능을 구현합니다.

## 📝 To-do
- [x] 로그인 API 구현
- [x] 회원가입 API 구현
- [x] 회원가입 시 랜덤 닉네임 생성 기능 구현
- [x] 토큰 재발급 API 구현
- [x] API별 권한 설정    

메소드 | API 엔드포인트 | 공개 범위
-- | -- | --
GET | /comments | 참여한 공고 만
POST | /comments | 참여한 공고 만
GET | /comments/offering-id | 참여한 공고 만
GET | /offerings | 전체 공개
POST | /offerings | 로그인 한 회원
GET | /offerings/offering-id | 전체 공개
GET | /offerings/product-images/og | 전체 공개
GET | /offerings/product-images/s3 | 전체 공개
GET | /offerings/{offering-id}/meetings | 참여한 공고 만
POST | /participations | 로그인 한 회원

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- `3h+`
