### ISSUE TITLE
✨ 상품 URL 이미지 추출 API 연결

### ISSUE THREAD

**Issue by chaehyuns** [woowacourse-teams/2024-chongdae-market#168]
## 📌 Description
- 상품 URL 이미지 추출 API 연결

## 📝 To-do
- [x] 상품 URL 이미지 추출 API 연결
- [x] 추출된 이미지 보이도록 view 구현
- [x] 이미지 삭제 로직 구현 

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- `3h+`
