### ISSUE TITLE
✨ 댓글방 디테일 화면 구현

### ISSUE THREAD

**Issue by chaehyuns** [woowacourse-teams/2024-chongdae-market#20]
## 📌 Description
- 댓글방의 현재 상태와 댓글 내용을 보여주는 화면을 구현해요

## 📝 To-do
- [x] 공구 현재 상태를 보여주는 뷰 구현
- [x] 약속 장소와 시간을 보여주는 접힐 수 있는 뷰 구현
- [x] 댓글 목록을 보여주는 view 구현

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- `2h`
- 2.5h
- 3h+
