### ISSUE TITLE
 ⚡ 공모 상세 화면 오류 수정

### ISSUE THREAD

**Issue by Namyunsuk** [woowacourse-teams/2024-chongdae-market#278]
## 📌 Description
- 공모 상세 화면 오류 수정

## 📝 To-do
- [ ] 총대 여부 확인 로직 수정
- [ ] productUrl -> productUrl?
- [ ] 마감 임박 상태 시 버튼 수정
- [ ] 공모 작성 -> 홈화면 돌아 올 때 새로고침 하도록 수정

## 예상 소요 시간
`- 0.5h`
- 1h
- 1.5h
- 2h
- 2.5h
- 3h+
