### ISSUE TITLE
✨ 댓글방 새로운 기능 GA 연결

### ISSUE THREAD

**Issue by chaehyuns** [woowacourse-teams/2024-chongdae-market#288]
## 📌 Description
- 댓글방 새로운 기능 GA 연결

## 📝 To-do
- [x] 댓글방 새로운 기능 GA Event 설정
- [x] 댓글방 참여자 확인 Event
- [x] 댓글방 상태 변경 취소 Event
- [x] 댓글방 상태 변경 확정 Event

## 예상 소요 시간
- 0.5h
- 1h
- `1.5h`
- 2h
- 2.5h
- 3h+
