### ISSUE TITLE
♻️ 홈화면 리팩토링

### ISSUE THREAD

**Issue by Namyunsuk** [woowacourse-teams/2024-chongdae-market#307]
## 📌 Description
-  홈화면 리팩토링

## 📝 To-do
- [x] 검색 버튼 키우기
- [x] 엔터 누르면 줄바꿈 되지 않고 검색 되도록 수정
- [x] 필터 하나만 선택 되도록 변경
- [x] sp -> dp

## 예상 소요 시간
- 0.5h
- 1h
`- 1.5h`
- 2h
- 2.5h
- 3h+
