### ISSUE TITLE
✨ 공모 상세 화면 추가 기능 반영

### ISSUE THREAD

**Issue by Namyunsuk** [woowacourse-teams/2024-chongdae-market#309]
## 📌 Description
- 공모 상세 화면 추가 기능 반영

## 📝 To-do
- [x] 내가 작성한 글에서 채팅방으로 이동하는 기능 구현
- [x] 내가 참여한 글에서 채팅방으로 이동하는 기능 구현
- [x] 마감시간 -> 거래날짜
- [x] 물품 링크 없을 시 보이지 않도록
- [x] 신고 링크 연결

## 예상 소요 시간
`- 0.5h`
- 1h
- 1.5h
- 2h
- 2.5h
- 3h+
