### ISSUE TITLE
✨ 댓글방 상태 조회 API를 댓글방 정보 조회 API로 확장

### ISSUE THREAD

**Issue by helenason** [woowacourse-teams/2024-chongdae-market#315]
## 📌 Description
- 기존 댓글방 상태 조회 API를 댓글방 정보 조회 API로 확장한다.
- 기존 (댓글방 상태 조회)
    ```json
    {
        "status": "GROUPING",
        "imageUrl": "https://d3a5rfnjdz82qu.cloudfront.net/chongdae-market/images/common/GROUPING.png",
        "buttonText": "인원확정"
     }
    ```
- 수정 (댓글방 정보 조회)
    ```json
    {
        "status": "GROUPING",
        "imageUrl": "https://d3a5rfnjdz82qu.cloudfront.net/chongdae-market/images/common/GROUPING.png",
        "buttonText": "인원확정",
        "message": "~~~~",
        "title": "공모글 제목입니다요",
        "isProposer": true
     }
    ```
    - 변경사항
        1. 이미지(imageUrl) 변경
        2. 확정 버튼 클릭 시 alert를 위한 메시지(message) 필드 추가
        3. 공모글 제목 추가
        4. 로그인 사용자의 총대 여부 판단

## 📝 To-do
- [x] 이미지(imageUrl) 변경
- [x] 확정 버튼 클릭 시 alert를 위한 메시지(message) 필드 추가
- [x] 공모글 제목 필드 추가
- [x] 로그인 사용자의 총대 여부 판단

## 예상 소요 시간
- 0.5h
- `1h`
- 1.5h
- 2h
- 2.5h
- 3h+
