### ISSUE TITLE
✨ 댓글방 참여자 확인 API 연결

### ISSUE THREAD

**Issue by chaehyuns** [woowacourse-teams/2024-chongdae-market#333]
## 📌 Description
- 댓글방 참여자 확인 API 연결

## 📝 To-do
- [x] 댓글방 참여자 목록 API 연결
- [x] 예상 엔빵 가격 확인 기능
- [x] 공동구매 참여 인원 확인 기능 
- [x] 더보기 버튼 수정
- [x] 공동구매 dialog 메시지 변경 (서버 지정 메시지)

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- `3h+`
