### ISSUE TITLE
♻️ 할인율 계산 로직 수정

### ISSUE THREAD

**Issue by helenason** [woowacourse-teams/2024-chongdae-market#357]
## 📌 Description
- 할인율 계산 로직 수정

## 📝 To-do
- [x] 할인율 계산 전 검증 로직 추가
- [x] 엔티티 생성 시 할인율 계산
- [x] 할인율 계산 시 소수점 둘째 자리에서 반올림

## 예상 소요 시간
- 0.5h
- `1h`
- 1.5h
- 2h
- 2.5h
- 3h+
