### ISSUE TITLE
✨ 홈 화면 UX개선

### ISSUE THREAD

**Issue by Namyunsuk** [woowacourse-teams/2024-chongdae-market#392]
## 📌 Description
- 홈 화면 UX개선

## 📝 To-do
- [x] 필터 텍스트 크기 키우기
- [x] 검색한 공모가 없을 시 명시적으로 알려주기.
- [x] 화면을 아래로 당기면 리스트가 새로고침 되도록 구현
- [x] 검색이 어떤 기준으로 진행되는지 placeholder로 명시하기
- [x] 검색창에 x버튼 만들기(클릭 시 검색 텍스트 지워짐  +  전체 공모 보여지는 초기화면보여주도록)

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
`- 2h`
- 2.5h
- 3h+
