### ISSUE TITLE
✨ 게시글 상세 화면 구현

### ISSUE THREAD

**Issue by Namyunsuk** [woowacourse-teams/2024-chongdae-market#4]
## 📌 Description
- 게시글 상세 화면 구현

## 📝 To-do
- [x] 게시물 상세 화면 뷰 작성
- [x] Data layer 코드 작성
- [x] Domain layer 코드 작성

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- `2.5h`
- 3h+
