### ISSUE TITLE
✨ Offering Entity에 Soft Delete 적용

### ISSUE THREAD

**Issue by masonkimseoul** [woowacourse-teams/2024-chongdae-market#482]
## 📌 Description
- Offering Entity에 Soft Delete 적용

## 📝 To-do
- [x] Offering Entity에 Soft Delete 상태를 식별할 수 있는 필드 추가
- [x] DB 스키마 칼럼 추가
- [ ] DEV -> PROD 적용

## 예상 소요 시간
- 0.5h
- `1h`
- 1.5h
- 2h
- 2.5h
- 3h+
