### ISSUE TITLE
✨ 공모 수정 API 구현

### ISSUE THREAD

**Issue by fromitive** [woowacourse-teams/2024-chongdae-market#484]
## 📌 Description
- 제약 조건에 따른 공모 수정 API를 구현합니다.

## 📝 To-do
- [x] 공모 상태가 모집중이 아닐 경우 수정 불가능
- [x] 총대가 아닌 참여자는 수정 불가능
- [x] 일부 필드는 부분적으로 수정 가능
    - [x] 총 인원수는 현재 모집집 된 인원 수 이하로 설정 불가
    - [x] 거래 일자는 수정 날짜 기준 내일 이상만 설정 가능
- [x] 원 가격이 N빵 가격 보다 작을 작을경우 수정 불가능 
- [x] 트렌젝션 범위 적용
- [x] 테스트 코드 작성
## 예상 소요 시간
- 0.5h
- 1h
- `1.5h`
- 2h
- 2.5h
- 3h+
