### ISSUE TITLE
♻️ OfferingRepository 쿼리 최적화

### ISSUE THREAD

**Issue by helenason** [woowacourse-teams/2024-chongdae-market#504]
## 📌 Description
- OfferingRepository 쿼리 최적화

## 📝 To-do
- [x] Member 더미데이터 1000건 생성
- [x] Offering 더미데이터 1,000,000건 생성
- [x] OfferingMember 더미데이터 약 5,000,000건 생성
- [ ] Comment 더미데이터 생성
- [ ] OfferingRepository 인덱스 추가 및 쿼리 최적화

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- `3h+`
