### ISSUE TITLE
♻️ OfferingMember를 Participant, Proposer 도메인으로 분리

### ISSUE THREAD

**Issue by ChooSeoyeon** [woowacourse-teams/2024-chongdae-market#536]
## 📌 Description
- OfferingMember 엔티티의 역할에 따라 도메인을 분리하고자 합니다.
- 리팩토링은 사전에 라이트닝 토크에서 발표했던 내용대로 진행할 예정입니다.
- 다른 도메인 리팩토링도 아래에 정리해둔 글 참고해서 진행해주심 좋을 거 같습니다! 여기서 레거시 리팩토링 2만 우선 적용하면 될 거 같습니다. 레거시 리팩토링 3는 추후 한 번 더 필요성 논의 후 적용합시다!
[도메인 리팩토링 ](https://choo.oopy.io/cbef24e7-d64c-47ac-bfc7-516a2ec72f9a#27c079f1-ff39-4a7e-8b8d-0661b16e3172)

## 📝 To-do
- [x] Member 도메인 관련한 아키텍처를 레거시 리팩토링 1, 2, 3의 방안으로 리팩토링한다
- [ ] OfferingMember 도메인 관련한 아키텍처를 레거시 리팩토링 2, 3의 방안으로 리팩토링한다
- [ ] Participant, Proposer 도메인을 분리한다

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- `2h`
- 2.5h
- 3h+
