### ISSUE TITLE
✨ 플레이스토어 딥링크 연결

### ISSUE THREAD

**Issue by chaehyuns** [woowacourse-teams/2024-chongdae-market#538]
## 📌 Description
- 플레이스토어 딥링크 연결해보아요

## 📝 To-do
- [ ] manifest 파일 수정
- [ ] MainActivity에서 OfferingDetail로 연결
- [ ] Play Console 딥링크 설정

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- `2h`
- 2.5h
- 3h+
