### ISSUE TITLE
✨ 딥링크 기능 구현

### ISSUE THREAD

**Issue by fromitive** [woowacourse-teams/2024-chongdae-market#541]
## 📌 Description
- 딥링크 기능을 구현해서 사용자 유치를 할 계획이에요
- 최종적으로 공유하기 기능을 구현해서 사람들에게 총대마켓을 효과적으로 홍보하는게 목표에요~ 

## 📝 To-do
- [x] 딥링크 전용 controller 개발
- [x] 안드로이드 선생님들과 협업
- [x] 백엔드 선생님들 분노하지 않게 리팩터링 하기

## 예상 소요 시간
- `0.5h`
- 1h
- 1.5h
- 2h
- 2.5h
- 3h+
