### ISSUE TITLE
✨ 안드로이드 FCM 구현

### ISSUE THREAD

**Issue by songpink** [woowacourse-teams/2024-chongdae-market#602]
## 📌 Description
- 안드로이드에서 FCM을 구현합니다.

## 📝 To-do
다음 기능에 푸시 알림 구현합니다.
- [ ] 내가 참여한 댓글방에 댓글이 달릴 시
- [ ] 내가 참여한 공동구매의 진행상태가 변경되었을 시
- [ ] 새로운 공모글이 업로드 되었을 시 (사용자가 적을 시기에만 임시적으로 적용할 예정)

적용할지 말지 고민중인 것
- 내가 참여한 댓글방에 다른 사람이 입장하거나 퇴장할 시

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- `3h+`
