### ISSUE TITLE
✨ swagger와 restdocs 연동

### ISSUE THREAD

**Issue by ChooSeoyeon** [woowacourse-teams/2024-chongdae-market#62]
## 📌 Description
- restdocs-api-spec을 이용해 OAS 출력하고, swagger와 연동합니다.

## 📝 To-do
- [x] swagger ui 정적 파일 설치 및 static routing 세팅
- [x] restdocs-api-spec을 이용한 OAS 생성
- [x] 생성된 OAS 파일을 Swagger 디렉터리로 복사하는 스크립트 작성
- [x] RestAssured RestDocs 테스트 코드 작성

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- `3h+`
