### ISSUE TITLE
✨ 공모 상세 페이지 기능 추가

### ISSUE THREAD

**Issue by Namyunsuk** [woowacourse-teams/2024-chongdae-market#84]
## 📌 Description
- 공모 상세 페이지 기능 추가

## 📝 To-do
- [x] 참여하기 버튼 클릭 시 채팅방을 가도록 구현
- [x] 바로가기 기능 구현
- [x] 신고하기 아이콘 추가

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
`- 2h`
- 2.5h
- 3h+
