### ISSUE TITLE
✨  댓글방 댓글 조회 api 연결

### ISSUE THREAD

**Issue by chaehyuns** [woowacourse-teams/2024-chongdae-market#97]
## 📌 Description
- 댓글방 댓글 조회 api 연결

## 📝 To-do
- [x] 댓글 조회 recycler view 구현
- [x] view type을 사용하여 상대방 댓글 view, 나의 댓글  view, 채팅 날짜 view를 다르게 보여준다. 
- [x] 1초에 1번씩 api를 호출하여 반실시간으로 구현한다

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- 2h
- 2.5h
- `3h+`
